package mvc.model.objects.enums;

public enum Tool {
    //Strumenti di una partita

    GROZING_PLIERS, EGLOMISE_BRUSH, COPPER_FOIL_BURNISHER, LATHEKIN, LENS_CUTTER, FLUX_BRUSH,
    GLAZING_HAMMER, RUNNING_PLIERS, CORK_BACKED_STRAIGHTEDGE, GRIDING_STONE, FLUX_REMOVER, TAP_WHEEL;
}
