package mvc.model.objects.enums;

public enum WindowPattern {
    //24 window pattern

    BELLESGUARD,
    FRACTAL_DROPS,
    LUZ_CELESTIAL,
    SUN_CATCHER,
    AURORA_SAGRADIS,
    CHROMATIC_SPLENDOR,
    KALEIDOSCOPIC_DREAM,
    VIA_LUX,
    AURORAE_MAGNIFICUS,
    BATTLO,
    COMITAS,
    FIRELIGHT,
    FIRMITAS,
    FULGOR_DEL_CIELO,
    GRAVITAS,
    INDUSTRIA,
    LUX_ASTRAM,
    RIPPLE_OF_LIGHT,
    SHADOW_THIEF,
    VIRTUS,
    SYMPHONY_OF_LIGHT,
    WATER_OF_LIGHT,
    LUX_MUNDI,
    SUNSS_GLORY
}

